# Generated by Django 5.0.2 on 2024-10-17 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=50)),
                ('Rimg', models.ImageField(upload_to='images/')),
                ('Rdesc', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('RcontactNumber', models.IntegerField()),
                ('Fooditems', models.ManyToManyField(to='food.fooditem')),
                ('Radmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('IsPayment', models.BooleanField(default=False)),
                ('OrderId', models.CharField(max_length=100)),
                ('Fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem')),
                ('Restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurent')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
