# Generated by Django 5.0.2 on 2024-10-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_person_isowner_restaurent_roders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fooditem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
