# Generated by Django 5.0.2 on 2024-10-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_orderitem_order_remove_orderitem_fooditem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roders',
        ),
    ]
