# Generated by Django 5.0.2 on 2024-10-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditionalFoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Additems', models.ManyToManyField(to='food.fooditem')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.order')),
            ],
        ),
    ]
