# Generated by Django 5.0.2 on 2024-10-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_aditionalfooditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
